name: flet_flip_counter
description: Flet FletFlipCounter control
repository: https://github.com/MyGithubAccount/flet-flip-counter/src/flutter/flet_flip_counter
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-flip-counter

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animated_flip_counter: ^0.3.4
  flet: 0.27.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
